-- ============================================================
-- Apotheca - item data for WoW: Forever
--
-- GENERATED by Tools/build_item_tables.py from docs/forever-consumables-69977.tsv
-- (client build 69977). Do not edit by hand: re-scan in game and
-- regenerate. Every value is what this client's own tooltip says.
-- ============================================================

Apotheca = Apotheca or {}
local D = {}
Apotheca.DATA = D

-- Health potions, strongest first (average of the tooltip range).
D.HEALTH_ITEMS = {
    223913, -- Major Healing Potion (1500)
    13446,  -- Major Healing Potion (1400)
    18253,  -- Major Rejuvenation Potion (1600)
    17348,  -- Major Healing Draught (1120)
    3928,   -- Superior Healing Potion (800)
    18839,  -- Combat Healing Potion (800)
    223914, -- Greater Healing Potion (650)
    17349,  -- Superior Healing Draught (640)
    274935, -- Tessa's Tonic (800)
    1710,   -- Greater Healing Potion (520)
    268883, -- Perishable Healing Potion (320)
    929,    -- Healing Potion (320)
    268882, -- Perishable Lesser Healing Potion (160)
    858,    -- Lesser Healing Potion (160)
    2456,   -- Minor Rejuvenation Potion (120)
    268881, -- Perishable Minor Healing Potion (80)
    118,    -- Minor Healing Potion (80)
    282011, -- Restored Healing Potion (30%)
}

-- Mana potions, strongest first.
D.MANA_ITEMS = {
    13444,  -- Major Mana Potion (1800)
    13443,  -- Superior Mana Potion (1200)
    18253,  -- Major Rejuvenation Potion (1600)
    18841,  -- Combat Mana Potion (1200)
    17351,  -- Major Mana Draught (1120)
    6149,   -- Greater Mana Potion (800)
    17352,  -- Superior Mana Draught (640)
    274935, -- Tessa's Tonic (800)
    3827,   -- Mana Potion (520)
    3385,   -- Lesser Mana Potion (320)
    2455,   -- Minor Mana Potion (160)
    3087,   -- Mug of Shimmer Stout (160)
    2456,   -- Minor Rejuvenation Potion (120)
    282013, -- Restored Mana Potion (20%)
}

-- Demonic Rune (12662) and Dark Rune (20520) were NOT in the client scan on
-- this build. Kept so the button works if they exist; they never match if not.
D.RUNE_ITEMS = { 20520, 12662 }

-- Items that collapse Food and Drink into one button. Empty on Forever: food
-- restoring both is listed on both buttons instead (restoresMana / restoresHealth).
D.CONJURED_ITEMS = {}

-- Plain drinks (no Well Fed), strongest first. Conjured = the tooltip says "Conjured Item".
D.DRINK_ITEMS = {
    { id = 227813, manaValue = 6363  },  -- Drinkable Stratholme Holy Water
    { id = 231778, manaValue = 4903 , conjured = true },  -- Mountain Spring Water
    { id = 13724 , manaValue = 4240 , restoresHealth = true },  -- Enriched Manna Biscuit
    { id = 19060 , manaValue = 4240 , restoresHealth = true },  -- Warsong Gulch Enriched Ration
    { id = 19301 , manaValue = 4240 , restoresHealth = true },  -- Alterac Manna Biscuit
    { id = 20031 , manaValue = 4240 , restoresHealth = true },  -- Essence Mango
    { id = 20062 , manaValue = 4240 , restoresHealth = true },  -- Arathi Basin Enriched Ration
    { id = 20222 , manaValue = 4240 , restoresHealth = true },  -- Defiler's Enriched Ration
    { id = 20225 , manaValue = 4240 , restoresHealth = true },  -- Highlander's Enriched Ration
    { id = 262433, manaValue = 4240 , restoresHealth = true },  -- Ketharas' Hyjal Stew
    { id = 272055, manaValue = 4240 , restoresHealth = true },  -- Darkspear Islands Enriched Ration
    { id = 8079  , manaValue = 4038 , conjured = true },  -- Conjured Crystal Water
    { id = 18300 , manaValue = 4038  },  -- Hyjal Nectar
    { id = 19061 , manaValue = 3178 , restoresHealth = true },  -- Warsong Gulch Iron Ration
    { id = 20064 , manaValue = 3178 , restoresHealth = true },  -- Arathi Basin Iron Ration
    { id = 20224 , manaValue = 3178 , restoresHealth = true },  -- Defiler's Iron Ration
    { id = 20227 , manaValue = 3178 , restoresHealth = true },  -- Highlander's Iron Ration
    { id = 272054, manaValue = 3178 , restoresHealth = true },  -- Darkspear Islands Iron Ration
    { id = 8078  , manaValue = 2821 , conjured = true },  -- Conjured Sparkling Water
    { id = 8766  , manaValue = 2821  },  -- Morning Glory Dew
    { id = 23161 , manaValue = 2821  },  -- Freshly-Squeezed Lemonade
    { id = 285359, manaValue = 2821  },  -- Warm Apple Juice
    { id = 19062 , manaValue = 2117 , restoresHealth = true },  -- Warsong Gulch Field Ration
    { id = 20063 , manaValue = 2117 , restoresHealth = true },  -- Arathi Basin Field Ration
    { id = 20223 , manaValue = 2117 , restoresHealth = true },  -- Defiler's Field Ration
    { id = 20226 , manaValue = 2117 , restoresHealth = true },  -- Highlander's Field Ration
    { id = 272053, manaValue = 2117 , restoresHealth = true },  -- Darkspear Islands Field Ration
    { id = 8077  , manaValue = 1915 , conjured = true },  -- Conjured Mineral Water
    { id = 1645  , manaValue = 1915  },  -- Moonberry Juice
    { id = 19300 , manaValue = 1915  },  -- Bottled Winterspring Water
    { id = 3772  , manaValue = 1292 , conjured = true },  -- Conjured Spring Water
    { id = 1708  , manaValue = 1292  },  -- Sweet Nectar
    { id = 4791  , manaValue = 1292  },  -- Enchanted Water
    { id = 2136  , manaValue = 803  , conjured = true },  -- Conjured Purified Water
    { id = 1205  , manaValue = 803   },  -- Melon Juice
    { id = 9451  , manaValue = 803   },  -- Bubbling Water
    { id = 19299 , manaValue = 803   },  -- Fizzy Faire Drink
    { id = 17747 , manaValue = 600  , restoresHealth = true },  -- Razorlash Root
    { id = 2288  , manaValue = 420  , conjured = true },  -- Conjured Fresh Water
    { id = 1179  , manaValue = 420   },  -- Ice Cold Milk
    { id = 17404 , manaValue = 420   },  -- Blended Bean Brew
    { id = 252027, manaValue = 420   },  -- Gustberry Juice
    { id = 3448  , manaValue = 282  , restoresHealth = true },  -- Senggin Root
    { id = 5350  , manaValue = 145  , conjured = true },  -- Conjured Water
    { id = 159   , manaValue = 145   },  -- Refreshing Spring Water
    { id = 252031, manaValue = 145   },  -- Crisp Spring Water
}

-- Plain food (no Well Fed), strongest first.
D.FOOD_ITEMS = {
    { id = 19301 , healthValue = 4240 , restoresMana = true },  -- Alterac Manna Biscuit
    { id = 262433, healthValue = 4240 , restoresMana = true },  -- Ketharas' Hyjal Stew
    { id = 22895 , healthValue = 3057 , conjured = true },  -- Conjured Cinnamon Roll
    { id = 20031 , healthValue = 2451 , restoresMana = true },  -- Essence Mango
    { id = 238637, healthValue = 2451  },  -- Prowler Steak
    { id = 238638, healthValue = 2451  },  -- Filet o' Flank
    { id = 238639, healthValue = 2451  },  -- Sunrise Omelette
    { id = 8076  , healthValue = 2065 , conjured = true },  -- Conjured Sweet Roll
    { id = 8932  , healthValue = 2065  },  -- Alterac Swiss
    { id = 8948  , healthValue = 2065  },  -- Dried King Bolete
    { id = 8950  , healthValue = 2065  },  -- Homemade Cherry Pie
    { id = 8952  , healthValue = 2065  },  -- Roasted Quail
    { id = 8953  , healthValue = 2065  },  -- Deep Fried Plantains
    { id = 11415 , healthValue = 2065  },  -- Mixed Berries
    { id = 11444 , healthValue = 2065  },  -- Grim Guzzler Boar
    { id = 12763 , healthValue = 2065  },  -- Un'Goro Etherfruit
    { id = 13724 , healthValue = 2065 , restoresMana = true },  -- Enriched Manna Biscuit
    { id = 16171 , healthValue = 2065  },  -- Shinsollo
    { id = 19060 , healthValue = 2065 , restoresMana = true },  -- Warsong Gulch Enriched Ration
    { id = 19225 , healthValue = 2065  },  -- Deep Fried Candybar
    { id = 20062 , healthValue = 2065 , restoresMana = true },  -- Arathi Basin Enriched Ration
    { id = 20222 , healthValue = 2065 , restoresMana = true },  -- Defiler's Enriched Ration
    { id = 20225 , healthValue = 2065 , restoresMana = true },  -- Highlander's Enriched Ration
    { id = 21031 , healthValue = 2065  },  -- Cabbage Kimchi
    { id = 21033 , healthValue = 2065  },  -- Radish Kimchi
    { id = 22324 , healthValue = 2065  },  -- Winter Kimchi
    { id = 23160 , healthValue = 2065  },  -- Friendship Bread
    { id = 250081, healthValue = 2065  },  -- Clam Linguine
    { id = 260627, healthValue = 2065  },  -- Savory Shen'dralar Steak
    { id = 260628, healthValue = 2065  },  -- Stuffed Pumpkin
    { id = 272055, healthValue = 2065 , restoresMana = true },  -- Darkspear Islands Enriched Ration
    { id = 278122, healthValue = 2065  },  -- Carrot Salad
    { id = 19061 , healthValue = 1546 , restoresMana = true },  -- Warsong Gulch Iron Ration
    { id = 20064 , healthValue = 1546 , restoresMana = true },  -- Arathi Basin Iron Ration
    { id = 20224 , healthValue = 1546 , restoresMana = true },  -- Defiler's Iron Ration
    { id = 20227 , healthValue = 1546 , restoresMana = true },  -- Highlander's Iron Ration
    { id = 272054, healthValue = 1546 , restoresMana = true },  -- Darkspear Islands Iron Ration
    { id = 8075  , healthValue = 1338 , conjured = true },  -- Conjured Sourdough
    { id = 3927  , healthValue = 1338  },  -- Fine Aged Cheddar
    { id = 4599  , healthValue = 1338  },  -- Cured Ham Steak
    { id = 4601  , healthValue = 1338  },  -- Soft Banana Bread
    { id = 4602  , healthValue = 1338  },  -- Moon Harvest Pumpkin
    { id = 4608  , healthValue = 1338  },  -- Raw Black Truffle
    { id = 9681  , healthValue = 1338  },  -- Grilled King Crawler Legs
    { id = 13546 , healthValue = 1338  },  -- Bloodbelly Fish
    { id = 13893 , healthValue = 1338  },  -- Large Raw Mightfish
    { id = 16168 , healthValue = 1338  },  -- Heaven Peach
    { id = 16766 , healthValue = 1338  },  -- Undermine Clam Chowder
    { id = 17408 , healthValue = 1338  },  -- Spicy Beefstick
    { id = 18255 , healthValue = 1338  },  -- Runn Tum Tuber
    { id = 18635 , healthValue = 1338  },  -- Bellara's Nutterbar
    { id = 19306 , healthValue = 1338  },  -- Crunchy Frog
    { id = 21030 , healthValue = 1338  },  -- Darnassus Kimchi Pie
    { id = 21552 , healthValue = 1338  },  -- Striped Yellowtail
    { id = 249796, healthValue = 1338  },  -- Hyjal Berries
    { id = 260624, healthValue = 1338  },  -- Pristine Peach
    { id = 260625, healthValue = 1338  },  -- Garnished Rice Cake
    { id = 19062 , healthValue = 1032 , restoresMana = true },  -- Warsong Gulch Field Ration
    { id = 20063 , healthValue = 1032 , restoresMana = true },  -- Arathi Basin Field Ration
    { id = 20223 , healthValue = 1032 , restoresMana = true },  -- Defiler's Field Ration
    { id = 20226 , healthValue = 1032 , restoresMana = true },  -- Highlander's Field Ration
    { id = 272053, healthValue = 1032 , restoresMana = true },  -- Darkspear Islands Field Ration
    { id = 1487  , healthValue = 841  , conjured = true },  -- Conjured Pumpernickel
    { id = 1707  , healthValue = 841   },  -- Stormwind Brie
    { id = 3771  , healthValue = 841   },  -- Wild Hog Shank
    { id = 4539  , healthValue = 841   },  -- Goldenbark Apple
    { id = 4544  , healthValue = 841   },  -- Mulgore Spice Bread
    { id = 4607  , healthValue = 841   },  -- Delicious Cave Mold
    { id = 6807  , healthValue = 841   },  -- Frog Leg Stew
    { id = 8543  , healthValue = 841   },  -- Underwater Mushroom Cap
    { id = 13755 , healthValue = 841   },  -- Raw Winter Squid
    { id = 16169 , healthValue = 841   },  -- Wild Ricecake
    { id = 17407 , healthValue = 841   },  -- Graccu's Homemade Meat Pie
    { id = 18632 , healthValue = 841   },  -- Moonbrook Riot Taffy
    { id = 19224 , healthValue = 841   },  -- Red Hot Wings
    { id = 249795, healthValue = 841   },  -- Flame Papaya
    { id = 260623, healthValue = 841   },  -- Candied Fruit Sampler
    { id = 278118, healthValue = 841   },  -- Rich Broth
    { id = 278120, healthValue = 841   },  -- Fruit Platter
    { id = 17747 , healthValue = 600  , restoresMana = true },  -- Razorlash Root
    { id = 1114  , healthValue = 530  , conjured = true },  -- Conjured Rye
    { id = 422   , healthValue = 530   },  -- Dwarven Mild
    { id = 1119  , healthValue = 530   },  -- Bottled Spirits
    { id = 3770  , healthValue = 530   },  -- Mutton Chop
    { id = 4538  , healthValue = 530   },  -- Snapvine Watermelon
    { id = 4542  , healthValue = 530   },  -- Moist Cornbread
    { id = 4606  , healthValue = 530   },  -- Spongy Morel
    { id = 5478  , healthValue = 530   },  -- Dig Rat Stew
    { id = 7228  , healthValue = 530   },  -- Tigule's Strawberry Ice Cream
    { id = 16170 , healthValue = 530   },  -- Steamed Mandu
    { id = 19305 , healthValue = 530   },  -- Pickled Kodo Foot
    { id = 249794, healthValue = 530   },  -- Tel'Abim Plantains
    { id = 278121, healthValue = 530   },  -- Smoked Sausage
    { id = 3448  , healthValue = 282  , restoresMana = true },  -- Senggin Root
    { id = 5473  , healthValue = 282   },  -- Scorpid Surprise
    { id = 1113  , healthValue = 234  , conjured = true },  -- Conjured Bread
    { id = 414   , healthValue = 234   },  -- Dalaran Sharp
    { id = 1326  , healthValue = 234   },  -- Sauteed Sunfish
    { id = 2287  , healthValue = 234   },  -- Haunch of Meat
    { id = 4537  , healthValue = 234   },  -- Tel'Abim Banana
    { id = 4541  , healthValue = 234   },  -- Freshly Baked Bread
    { id = 4605  , healthValue = 234   },  -- Red-speckled Mushroom
    { id = 5066  , healthValue = 234   },  -- Fissure Plant
    { id = 5526  , healthValue = 234   },  -- Clam Chowder
    { id = 12238 , healthValue = 234   },  -- Darkshore Grouper
    { id = 16167 , healthValue = 234   },  -- Versicolor Treat
    { id = 17119 , healthValue = 234   },  -- Deeprun Rat Kabob
    { id = 17406 , healthValue = 234   },  -- Holiday Cheesewheel
    { id = 18633 , healthValue = 234   },  -- Styleen's Sour Suckerpop
    { id = 19304 , healthValue = 234   },  -- Spiced Beef Jerky
    { id = 249793, healthValue = 234   },  -- Wayward Pomegranate
    { id = 252026, healthValue = 234   },  -- Gustberry Pie
    { id = 252029, healthValue = 234   },  -- Hippogryph Flank
    { id = 252030, healthValue = 234   },  -- Pungent Skycheddar
    { id = 252032, healthValue = 234   },  -- Red Delicious Stormapple
    { id = 278117, healthValue = 234   },  -- Hard Boiled Eggs
    { id = 5349  , healthValue = 58   , conjured = true },  -- Conjured Muffin
    { id = 117   , healthValue = 58    },  -- Tough Jerky
    { id = 961   , healthValue = 58    },  -- Healing Herb
    { id = 2070  , healthValue = 58    },  -- Darnassian Bleu
    { id = 2679  , healthValue = 58    },  -- Charred Wolf Meat
    { id = 4536  , healthValue = 58    },  -- Shiny Red Apple
    { id = 4540  , healthValue = 58    },  -- Tough Hunk of Bread
    { id = 4604  , healthValue = 58    },  -- Forest Mushroom Cap
    { id = 4656  , healthValue = 58    },  -- Small Pumpkin
    { id = 5057  , healthValue = 58    },  -- Ripe Watermelon
    { id = 5525  , healthValue = 58    },  -- Boiled Clams
    { id = 6458  , healthValue = 58    },  -- Oil Covered Fish
    { id = 7097  , healthValue = 58    },  -- Leg Meat
    { id = 16166 , healthValue = 58    },  -- Bean Soup
    { id = 17344 , healthValue = 58    },  -- Candy Cane
    { id = 19223 , healthValue = 58    },  -- Darkmoon Dog
    { id = 240945, healthValue = 58    },  -- Slice of Carrie's Apple Pie
    { id = 249792, healthValue = 58    },  -- Sweetsour Grapes
    { id = 251917, healthValue = 58    },  -- Falorne's Homemade Tart
    { id = 252022, healthValue = 58    },  -- Galestrider Jerky
    { id = 252023, healthValue = 58    },  -- Zaalanarr Sharp
    { id = 252028, healthValue = 58    },  -- Fresh Gustberry Bread
    { id = 267474, healthValue = 58    },  -- Galeswept Forestshroom
    { id = 278119, healthValue = 58    },  -- Bread with Butter
    { id = 278569, healthValue = 58    },  -- Yesterday's Leftovers
    { id = 6299  , healthValue = 28    },  -- Sickly Looking Fish
    { id = 11109 , healthValue = 28    },  -- Special Chicken Feed
    { id = 249791, healthValue = 28    },  -- Shiny Green Apple
    { id = 278265, healthValue = 28    },  -- Nutritious Slime Sludge
}

-- Well Fed food and drink, by the stat the buff grants. value = stat amount.
-- Forever buff food also restores health or mana while you eat.
D.BUFF_FOOD_BY_STAT = {
    agility = {
        { id = 250069, value = 20  },  -- Flank au Poivre (L45)
        { id = 250072, value = 20  },  -- Swiftstrike Steak (L45)
        { id = 12212 , value = 15  },  -- Jungle Stew (L35)
        { id = 18045 , value = 15  },  -- Tender Wolf Steak (L35)
        { id = 3728  , value = 10  },  -- Tasty Lion Steak (L25)
        { id = 13851 , value = 10  },  -- Hot Wolf Ribs (L25)
        { id = 20074 , value = 10  },  -- Heavy Crocolisk Stew (L25)
        { id = 1017  , value = 5   },  -- Seasoned Wolf Kabob (L15)
        { id = 3664  , value = 5   },  -- Crocolisk Gumbo (L15)
        { id = 3727  , value = 5   },  -- Hot Lion Chops (L15)
        { id = 12209 , value = 5   },  -- Lean Wolf Steak (L15)
        { id = 2684  , value = 3   },  -- Coyote Steak (L5)
        { id = 3662  , value = 3   },  -- Crocolisk Steak (L5)
        { id = 2680  , value = 1   },  -- Spiced Wolf Meat (L0)
    },
    armor = {
        { id = 286152, value = 150 },  -- Plated Armorfish (L35)
    },
    attackPower = {
        { id = 13932 , value = 40  },  -- Poached Sunscale Salmon (L35)
        { id = 13934 , value = 40  },  -- Mightfish Steak (L45)
        { id = 13927 , value = 30  },  -- Cooked Glossy Mightfish (L35)
        { id = 8364  , value = 20  },  -- Mithril Head Trout (L25)
        { id = 4592  , value = 10  },  -- Longjaw Mud Snapper (L5)
        { id = 787   , value = 6   },  -- Slitherskin Mackerel (L0)
        { id = 6290  , value = 2   },  -- Brilliant Smallfish (L0)
    },
    crit = {
        { id = 13928 , value = 1   },  -- Grilled Squid (L35)
        { id = 13929 , value = 1   },  -- Hot Smoked Bass (L35)
    },
    healing = {
        { id = 249870, value = 44  },  -- Sage's Tea (L45)
        { id = 249869, value = 33  },  -- Sunny Tea (L35)
        { id = 249868, value = 22  },  -- Triage Tea (L25)
        { id = 232438, value = 22  },  -- Smoked Redgill (L35)
        { id = 249867, value = 11  },  -- Root Tea (L15)
        { id = 249866, value = 7   },  -- Royal Tea (L5)
        { id = 249865, value = 2   },  -- Peace Tea (L0)
    },
    intellect = {
        { id = 250066, value = 20  },  -- Soaring Pamplona (L45)
        { id = 250067, value = 20  },  -- Bat Hachee (L45)
        { id = 250075, value = 20  },  -- Prehistoric Pulled Raptor (L45)
        { id = 18254 , value = 15  },  -- Runn Tum Tuber Surprise (L35)
        { id = 250076, value = 15  },  -- Raptor Rouladen (L35)
        { id = 4457  , value = 10  },  -- Barbecued Buzzard Wing (L25)
        { id = 12216 , value = 10  },  -- Spiced Chili Crab (L25)
        { id = 250073, value = 10  },  -- Raging Raptor Ribs (L25)
        { id = 12210 , value = 5   },  -- Roast Raptor (L15)
        { id = 1082  , value = 3   },  -- Redridge Goulash (L5)
        { id = 2683  , value = 3   },  -- Crab Cake (L5)
        { id = 250077, value = 3   },  -- Twice-Spiced Raptor Slice (L5)
        { id = 2682  , value = 1   },  -- Cooked Crab Claw (L0)
        { id = 5477  , value = 1   },  -- Strider Stew (L0)
        { id = 12224 , value = 1   },  -- Crispy Bat Wing (L0)
        { id = 250079, value = 1   },  -- Tasty Raptor Bites (L0)
        { id = 263512, value = 1   },  -- Pincer Bites (L5)
    },
    mp5 = {
        { id = 23176 , value = 6   },  -- Fizzy Energy Drink (L0)
    },
    spellDmg = {
        { id = 13933 , value = 28  },  -- Lobster Stew (L45)
        { id = 13935 , value = 28  },  -- Baked Salmon (L45)
        { id = 6887  , value = 22  },  -- Spotted Yellowtail (L35)
        { id = 13931 , value = 22  },  -- Nightfin Soup (L35)
        { id = 274971, value = 14  },  -- Briny Seafood Stew (L25)
        { id = 232436, value = 12  },  -- Darkclaw Bisque (L45)
        { id = 21217 , value = 7   },  -- Sagefish Delight (L30)
        { id = 21072 , value = 4   },  -- Smoked Sagefish (L10)
        { id = 5095  , value = 1   },  -- Rainbow Fin Albacore (L5)
    },
    spirit = {
        { id = 249876, value = 20  },  -- Wicked Smoothie (L45)
        { id = 249875, value = 15  },  -- Spicy Smoothie (L35)
        { id = 16971 , value = 12  },  -- Clamlette Surprise (L40)
        { id = 249874, value = 10  },  -- Calcified Smoothie (L25)
        { id = 13813 , value = 10  },  -- Blessed Sunfruit Juice (L45)
        { id = 19318 , value = 10  },  -- Bottled Alterac Spring Water (L55)
        { id = 5527  , value = 6   },  -- Goblin Deviled Clams (L15)
        { id = 248613, value = 6   },  -- Lightning in a Bottle (L15)
        { id = 249873, value = 5   },  -- Mrrggl Smrrthle (L15)
        { id = 249872, value = 3   },  -- Slimy Smoothie (L5)
        { id = 7806  , value = 2   },  -- Lollipop (L0)
        { id = 7807  , value = 2   },  -- Candy Bar (L0)
        { id = 7808  , value = 2   },  -- Chocolate Square (L0)
        { id = 11584 , value = 2   },  -- Cactus Apple Surprise (L0)
        { id = 17197 , value = 2   },  -- Gingerbread Cookie (L0)
        { id = 17198 , value = 2   },  -- Egg Nog (L0)
        { id = 206177, value = 2   },  -- Pine Nut Butter (L0)
        { id = 249871, value = 1   },  -- Venomous Smoothie (L0)
    },
    stamina = {
        { id = 21023 , value = 25  },  -- Dirge's Kickin' Chimaerok Chops (L45)
        { id = 250068, value = 20  },  -- Savory Turtle Stew (L45)
        { id = 12218 , value = 15  },  -- Monster Omelet (L35)
        { id = 17222 , value = 15  },  -- Spider Sausage (L35)
        { id = 16971 , value = 12  },  -- Clamlette Surprise (L40)
        { id = 6038  , value = 10  },  -- Giant Clam Scorcho (L25)
        { id = 12215 , value = 10  },  -- Heavy Kodo Stew (L25)
        { id = 250078, value = 10  },  -- Giant Scrambled Eggs (L25)
        { id = 11950 , value = 10  },  -- Windblossom Berries (L45)
        { id = 5527  , value = 6   },  -- Goblin Deviled Clams (L15)
        { id = 248613, value = 6   },  -- Lightning in a Bottle (L15)
        { id = 3665  , value = 5   },  -- Curiously Tasty Omelet (L15)
        { id = 3666  , value = 5   },  -- Gooey Spider Cake (L15)
        { id = 3729  , value = 5   },  -- Soothing Turtle Bisque (L15)
        { id = 12214 , value = 5   },  -- Mystery Stew (L15)
        { id = 5479  , value = 3   },  -- Crispy Lizard Tail (L5)
        { id = 12213 , value = 3   },  -- Carrion Surprise (L5)
        { id = 250080, value = 3   },  -- Breakfast Omelette (L5)
        { id = 268912, value = 3   },  -- Expiring Crab Cake (L5)
        { id = 268913, value = 3   },  -- Expiring Crocolisk Steak (L5)
        { id = 7806  , value = 2   },  -- Lollipop (L0)
        { id = 7807  , value = 2   },  -- Candy Bar (L0)
        { id = 7808  , value = 2   },  -- Chocolate Square (L0)
        { id = 11584 , value = 2   },  -- Cactus Apple Surprise (L0)
        { id = 17197 , value = 2   },  -- Gingerbread Cookie (L0)
        { id = 17198 , value = 2   },  -- Egg Nog (L0)
        { id = 206177, value = 2   },  -- Pine Nut Butter (L0)
        { id = 3663  , value = 1   },  -- Murloc Fin Soup (L0)
        { id = 5472  , value = 1   },  -- Kaldorei Spider Kabob (L0)
        { id = 5474  , value = 1   },  -- Roasted Kodo Meat (L0)
        { id = 6888  , value = 1   },  -- Herb Baked Egg (L0)
        { id = 263509, value = 1   },  -- Skywall Souffle (L5)
    },
    strength = {
        { id = 20452 , value = 20  },  -- Smoked Desert Dumplings (L45)
        { id = 250070, value = 20  },  -- Bear Bruscitti (L45)
        { id = 250071, value = 20  },  -- Steaming Stag Steak (L45)
        { id = 250065, value = 15  },  -- Savory Stag Sliders (L35)
        { id = 250074, value = 10  },  -- Bear Brisket (L25)
        { id = 274976, value = 10  },  -- Plain Ol' Paletusk (L25)
        { id = 13810 , value = 10  },  -- Blessed Sunfruit (L45)
        { id = 2685  , value = 5   },  -- Succulent Pork Ribs (L15)
        { id = 5480  , value = 5   },  -- Lean Venison (L15)
        { id = 724   , value = 3   },  -- Goretusk Liver Pie (L5)
        { id = 2687  , value = 3   },  -- Dry Pork Ribs (L5)
        { id = 3220  , value = 3   },  -- Blood Sausage (L5)
        { id = 3726  , value = 3   },  -- Big Bear Steak (L5)
        { id = 2681  , value = 1   },  -- Roasted Boar Meat (L0)
        { id = 2888  , value = 1   },  -- Beer Basted Boar Ribs (L0)
        { id = 6890  , value = 1   },  -- Smoked Bear Meat (L0)
    },
}

-- Every healthstone, strongest first. All ranks share one cooldown.
D.HEALTHSTONE_ITEMS = {
    { id = 9421  , healValue = 1440  },  -- Major Healthstone
    { id = 19013 , healValue = 1440  },  -- Major Healthstone
    { id = 19012 , healValue = 1320  },  -- Major Healthstone
    { id = 5510  , healValue = 960   },  -- Greater Healthstone
    { id = 19011 , healValue = 960   },  -- Greater Healthstone
    { id = 19010 , healValue = 880   },  -- Greater Healthstone
    { id = 5509  , healValue = 600   },  -- Healthstone
    { id = 19009 , healValue = 600   },  -- Healthstone
    { id = 19008 , healValue = 550   },  -- Healthstone
    { id = 5511  , healValue = 300   },  -- Lesser Healthstone
    { id = 19007 , healValue = 300   },  -- Lesser Healthstone
    { id = 19006 , healValue = 275   },  -- Lesser Healthstone
    { id = 5512  , healValue = 120   },  -- Minor Healthstone
    { id = 19005 , healValue = 120   },  -- Minor Healthstone
    { id = 19004 , healValue = 110   },  -- Minor Healthstone
}

-- Bandages, strongest first. Battleground ones are gated in ZONE_RESTRICTED_ITEMS.
D.BANDAGE_ITEMS = {
    232433, -- Dense Runecloth Bandage (3400)
    23684,  -- Crystal Infused Bandage (2500)
    14530,  -- Heavy Runecloth Bandage (2000)
    19066,  -- Warsong Gulch Runecloth Bandage (2000)
    19307,  -- Alterac Heavy Runecloth Bandage (2000)
    20066,  -- Arathi Basin Runecloth Bandage (2000)
    20234,  -- Defiler's Runecloth Bandage (2000)
    20243,  -- Highlander's Runecloth Bandage (2000)
    272058, -- Darkspear Islands Runecloth Bandage (2000)
    14529,  -- Runecloth Bandage (1360)
    8545,   -- Heavy Mageweave Bandage (1104)
    19067,  -- Warsong Gulch Mageweave Bandage (1104)
    20065,  -- Arathi Basin Mageweave Bandage (1104)
    20232,  -- Defiler's Mageweave Bandage (1104)
    20237,  -- Highlander's Mageweave Bandage (1104)
    272057, -- Darkspear Islands Mageweave Bandage (1104)
    8544,   -- Mageweave Bandage (800)
    6451,   -- Heavy Silk Bandage (640)
    19068,  -- Warsong Gulch Silk Bandage (640)
    20067,  -- Arathi Basin Silk Bandage (640)
    20235,  -- Defiler's Silk Bandage (640)
    20244,  -- Highlander's Silk Bandage (640)
    272056, -- Darkspear Islands Silk Bandage (640)
    6450,   -- Silk Bandage (400)
    3531,   -- Heavy Wool Bandage (301)
    3530,   -- Wool Bandage (161)
    2581,   -- Heavy Linen Bandage (114)
    1251,   -- Linen Bandage (66)
}

-- Buff scrolls by stat, strongest first. spell = the buff's spell ID.
D.SCROLLS_BY_STAT = {
    agility = {
        { id = 10309 , value = 17  , spell = 12174 },  -- Scroll of Agility IV
        { id = 4425  , value = 13  , spell = 8117 },  -- Scroll of Agility III
        { id = 1477  , value = 9   , spell = 8116 },  -- Scroll of Agility II
        { id = 3012  , value = 5   , spell = 8115 },  -- Scroll of Agility
    },
    armor = {
        { id = 10305 , value = 240 , spell = 12175 },  -- Scroll of Protection IV
        { id = 4421  , value = 180 , spell = 8095 },  -- Scroll of Protection III
        { id = 1478  , value = 120 , spell = 8094 },  -- Scroll of Protection II
        { id = 3013  , value = 60  , spell = 8091 },  -- Scroll of Protection
    },
    intellect = {
        { id = 10308 , value = 16  , spell = 12176 },  -- Scroll of Intellect IV
        { id = 4419  , value = 12  , spell = 8098 },  -- Scroll of Intellect III
        { id = 2290  , value = 8   , spell = 8097 },  -- Scroll of Intellect II
        { id = 955   , value = 4   , spell = 8096 },  -- Scroll of Intellect
    },
    spirit = {
        { id = 10306 , value = 15  , spell = 12177 },  -- Scroll of Spirit IV
        { id = 4424  , value = 11  , spell = 8114 },  -- Scroll of Spirit III
        { id = 1712  , value = 7   , spell = 8113 },  -- Scroll of Spirit II
        { id = 1181  , value = 3   , spell = 8112 },  -- Scroll of Spirit
    },
    stamina = {
        { id = 10307 , value = 16  , spell = 12178 },  -- Scroll of Stamina IV
        { id = 4422  , value = 12  , spell = 8101 },  -- Scroll of Stamina III
        { id = 1711  , value = 8   , spell = 8100 },  -- Scroll of Stamina II
        { id = 1180  , value = 4   , spell = 8099 },  -- Scroll of Stamina
    },
    strength = {
        { id = 10310 , value = 17  , spell = 12179 },  -- Scroll of Strength IV
        { id = 4426  , value = 13  , spell = 8120 },  -- Scroll of Strength III
        { id = 2289  , value = 9   , spell = 8119 },  -- Scroll of Strength II
        { id = 954   , value = 5   , spell = 8118 },  -- Scroll of Strength
    },
}

-- Every elixir and flask, tagged by stat. spell = the buff's spell ID, which
-- is how an active buff is recognised on any client language.
D.ELIXIR_CATALOG = {
    { id = 2454  , spell = 2367,   flask = false, level = 0 , stats = { strength = 4 } },  -- Elixir of Minor Strength
    { id = 2457  , spell = 2374,   flask = false, level = 2 , stats = { agility = 4 } },  -- Elixir of Minor Agility
    { id = 2458  , spell = 2378,   flask = false, level = 2 , stats = { maxHealth = 27 } },  -- Elixir of Minor Fortitude
    { id = 3382  , spell = 3219,   flask = false, level = 0 , stats = { hp5 = 2 } },  -- Minor Troll's Blood Elixir
    { id = 3383  , spell = 3166,   flask = false, level = 10, stats = { intellect = 6 } },  -- Elixir of Wisdom
    { id = 3388  , spell = 3222,   flask = false, level = 15, stats = { hp5 = 6 } },  -- Lesser Troll's Blood Elixir
    { id = 3389  , spell = 3220,   flask = false, level = 16, stats = { armor = 150 } },  -- Elixir of Lesser Defense
    { id = 3390  , spell = 3160,   flask = false, level = 18, stats = { agility = 8 } },  -- Elixir of Lesser Agility
    { id = 3391  , spell = 3164,   flask = false, level = 20, stats = { strength = 8 } },  -- Elixir of Ogre Strength
    { id = 3825  , spell = 3593,   flask = false, level = 25, stats = { maxHealth = 120 } },  -- Elixir of Lesser Fortitude
    { id = 3826  , spell = 3223,   flask = false, level = 26, stats = { hp5 = 12 } },  -- Troll's Blood Elixir
    { id = 5997  , spell = 673,    flask = false, level = 0 , stats = { armor = 50 } },  -- Elixir of Minor Defense
    { id = 6373  , spell = 7844,   flask = false, level = 18, stats = { spellDmgFire = 10 } },  -- Elixir of Fire Power
    { id = 8949  , spell = 11328,  flask = false, level = 27, stats = { agility = 15 } },  -- Elixir of Agility
    { id = 8951  , spell = 11349,  flask = false, level = 29, stats = { armor = 250 } },  -- Elixir of Defense
    { id = 9155  , spell = 11390,  flask = false, level = 37, stats = { spellDmg = 20 } },  -- Arcane Elixir
    { id = 9179  , spell = 11396,  flask = false, level = 37, stats = { intellect = 25 } },  -- Elixir of Greater Intellect
    { id = 9187  , spell = 11334,  flask = false, level = 38, stats = { agility = 25 } },  -- Elixir of Greater Agility
    { id = 9206  , spell = 11405,  flask = false, level = 48, stats = { strength = 25 } },  -- Elixir of Greater Strength
    { id = 9264  , spell = 11474,  flask = false, level = 40, stats = { spellDmgShadow = 40 } },  -- Elixir of Shadow Power
    { id = 12820 , spell = 17038,  flask = false, level = 45, stats = { attackPower = 35 } },  -- Winterfall Firewater
    { id = 13445 , spell = 11348,  flask = false, level = 43, stats = { armor = 450 } },  -- Elixir of Greater Defense
    { id = 13447 , spell = 17535,  flask = false, level = 38, stats = { intellect = 18, spirit = 18 } },  -- Elixir of the Sages
    { id = 13452 , spell = 17538,  flask = false, level = 46, stats = { agility = 25, crit = 2 } },  -- Elixir of the Mongoose
    { id = 13453 , spell = 17537,  flask = false, level = 45, stats = { stamina = 18, strength = 18 } },  -- Elixir of Brute Force
    { id = 13454 , spell = 17539,  flask = false, level = 47, stats = { spellDmg = 35 } },  -- Greater Arcane Elixir
    { id = 13510 , spell = 17626,  flask = true , level = 50, stats = { maxHealth = 1200 } },  -- Flask of the Titans
    { id = 13511 , spell = 17627,  flask = true , level = 50, stats = { maxMana = 2000 } },  -- Flask of Distilled Wisdom
    { id = 13512 , spell = 17628,  flask = true , level = 50, stats = { spellDmg = 150 } },  -- Flask of Supreme Power
    { id = 17708 , spell = 21920,  flask = false, level = 28, stats = { spellDmgFrost = 15 } },  -- Elixir of Frost Power
    { id = 20004 , spell = 24361,  flask = false, level = 53, stats = { hp5 = 20 } },  -- Major Troll's Blood Elixir
    { id = 20007 , spell = 24363,  flask = false, level = 40, stats = { mp5 = 12 } },  -- Mageblood Elixir
    { id = 21546 , spell = 1310077, flask = false, level = 40, stats = { spellDmgHoly = 40 } },  -- Elixir of Holy Power
    { id = 217398, spell = 439959, flask = false, level = 28, stats = { spellDmg = 14 } },  -- Lesser Arcane Elixir
    { id = 246948, spell = 17038,  flask = false, level = 45, stats = { attackPower = 35 } },  -- Distilled Firewater
    { id = 247754, spell = 1245244, flask = false, level = 0 , stats = { spellDmg = 5 } },  -- Minor Arcane Elixir
    { id = 250328, spell = 1250918, flask = false, level = 55, stats = { agility = 25, intellect = 25 } },  -- Elixir of Cunning
    { id = 250329, spell = 1250920, flask = false, level = 55, stats = { armor = 500, maxHealth = 400 } },  -- Elixir of the Phalanx
    { id = 250330, spell = 1250922, flask = false, level = 5 , stats = { healing = 10 } },  -- Minor Cleric's Elixir
    { id = 250331, spell = 1250924, flask = false, level = 25, stats = { healing = 20 } },  -- Lesser Cleric's Elixir
    { id = 250332, spell = 1250925, flask = false, level = 45, stats = { healing = 30 } },  -- Cleric's Elixir
    { id = 250333, spell = 1250926, flask = false, level = 55, stats = { healing = 40 } },  -- Greater Cleric's Elixir
    { id = 250334, spell = 1250928, flask = false, level = 45, stats = { maxHealth = 200 } },  -- Elixir of Fortitude
    { id = 250335, spell = 1250931, flask = false, level = 55, stats = { maxHealth = 400 } },  -- Elixir of Greater Fortitude
    { id = 250336, spell = 1250932, flask = false, level = 55, stats = { hp5 = 9, mp5 = 10 } },  -- Elixir of Wicked Regeneration
    { id = 250337, spell = 1250940, flask = false, level = 55, stats = { crit = 2, intellect = 25 } },  -- Elixir of the Owl
    { id = 250338, spell = 1250941, flask = false, level = 55, stats = { crit = 2, spirit = 25 } },  -- Elixir of Sages
    { id = 250339, spell = 1250942, flask = false, level = 5 , stats = { mp5 = 3 } },  -- Minor Mageblood Elixir
    { id = 250340, spell = 1250944, flask = false, level = 25, stats = { mp5 = 6 } },  -- Lesser Mageblood Elixir
    { id = 250341, spell = 1250948, flask = false, level = 55, stats = { mp5 = 20 } },  -- Greater Mageblood Elixir
    { id = 250342, spell = 1250971, flask = false, level = 25, stats = { spellDmg = 15 } },  -- Lesser Arcane Elixir
    { id = 250343, spell = 1250972, flask = false, level = 55, stats = { spellDmgNature = 40 } },  -- Elixir of Nature Power
    { id = 250344, spell = 1250974, flask = false, level = 5 , stats = { spirit = 3 } },  -- Elixir of Minor Spirit
    { id = 250345, spell = 1250976, flask = false, level = 25, stats = { spirit = 6 } },  -- Elixir of Lesser Spirit
    { id = 250346, spell = 1250978, flask = false, level = 45, stats = { spirit = 10 } },  -- Elixir of Spirit
    { id = 250347, spell = 1250979, flask = false, level = 55, stats = { spirit = 18 } },  -- Elixir of Greater Spirit
    { id = 250348, spell = 1250981, flask = false, level = 55, stats = { crit = 2, spirit = 25 } },  -- Elixir of the Whale
    { id = 250349, spell = 1250984, flask = false, level = 45, stats = { strength = 10 } },  -- Elixir of Strength
    { id = 250350, spell = 1250985, flask = false, level = 55, stats = { agility = 18, strength = 18 } },  -- Elixir of Ferocity
    { id = 250351, spell = 1250986, flask = false, level = 55, stats = { crit = 2, strength = 25 } },  -- Elixir of the Grizzly
    { id = 250353, spell = 1250988, flask = false, level = 25, stats = { intellect = 6 } },  -- Elixir of Lesser Intellect
    { id = 250354, spell = 1250989, flask = false, level = 45, stats = { intellect = 10 } },  -- Elixir of Intellect
    { id = 274273, spell = 1293740, flask = true , level = 55, stats = { stamina = 60 } },  -- Flask of Natural Accuracy
    { id = 274274, spell = 1293741, flask = true , level = 55, stats = { stamina = 60 } },  -- Flask of Natural Aggression
    { id = 274275, spell = 1293742, flask = true , level = 55, stats = { stamina = 60 } },  -- Flask of Natural Precision
    { id = 274276, spell = 1293743, flask = true , level = 55, stats = { stamina = 60 } },  -- Flask of Natural Swiftness
}

-- Weapon oils. kind = "mana" (healer default) or "wizard".
D.OILS = {
    { id = 20749 , kind = "wizard", stats = { healing = 36, spellCrit = 1, spellDmg = 36 } },  -- Brilliant Wizard Oil
    { id = 20750 , kind = "wizard", stats = { healing = 30, spellDmg = 30 } },  -- Wizard Oil
    { id = 20748 , kind = "mana",  stats = { healing = 30, mp5 = 15 } },  -- Brilliant Mana Oil
    { id = 20744 , kind = "wizard", stats = { healing = 15, spellDmg = 15 } },  -- Minor Wizard Oil
    { id = 20745 , kind = "mana",  stats = { healing = 10, mp5 = 5 } },  -- Minor Mana Oil
}

-- Items usable only in battlegrounds. "pvp" = any battleground; otherwise
-- { map = instance map ID (8th return of GetInstanceInfo), name = enUS name }.
-- map nil = not measured yet: the name is the only (enUS-only) match.
D.ZONE_RESTRICTED_ITEMS = {
    [17348] = "pvp",
    [17349] = "pvp",
    [17351] = "pvp",
    [17352] = "pvp",
    [19060] = { map = 489, name = "Warsong Gulch" },
    [19061] = { map = 489, name = "Warsong Gulch" },
    [19062] = { map = 489, name = "Warsong Gulch" },
    [19066] = { map = 489, name = "Warsong Gulch" },
    [19067] = { map = 489, name = "Warsong Gulch" },
    [19068] = { map = 489, name = "Warsong Gulch" },
    [19307] = { map = 30, name = "Alterac Valley" },
    [20062] = { map = 529, name = "Arathi Basin" },
    [20063] = { map = 529, name = "Arathi Basin" },
    [20064] = { map = 529, name = "Arathi Basin" },
    [20065] = { map = 529, name = "Arathi Basin" },
    [20066] = { map = 529, name = "Arathi Basin" },
    [20067] = { map = 529, name = "Arathi Basin" },
    [20222] = { map = 529, name = "Arathi Basin" },
    [20223] = { map = 529, name = "Arathi Basin" },
    [20224] = { map = 529, name = "Arathi Basin" },
    [20225] = { map = 529, name = "Arathi Basin" },
    [20226] = { map = 529, name = "Arathi Basin" },
    [20227] = { map = 529, name = "Arathi Basin" },
    [20232] = { map = 529, name = "Arathi Basin" },
    [20234] = { map = 529, name = "Arathi Basin" },
    [20235] = { map = 529, name = "Arathi Basin" },
    [20237] = { map = 529, name = "Arathi Basin" },
    [20243] = { map = 529, name = "Arathi Basin" },
    [20244] = { map = 529, name = "Arathi Basin" },
    [272053] = { map = nil, name = "Darkspear Islands" },
    [272054] = { map = nil, name = "Darkspear Islands" },
    [272055] = { map = nil, name = "Darkspear Islands" },
    [272056] = { map = nil, name = "Darkspear Islands" },
    [272057] = { map = nil, name = "Darkspear Islands" },
    [272058] = { map = nil, name = "Darkspear Islands" },
}
