"""
consumables_reference.py - write a readable catalog of every consumable the
client reports, for C:\\Projects\\References.

    python Tools/consumables_reference.py docs/forever-consumables-69977.tsv \\
        C:/Projects/References/forever-consumables-1.60.1.69977.md

The catalog is a snapshot of one client build, like the API dumps. After a
new build, re-scan in game (/apo scan, /apo scan2, /reload), re-export, and
write a new file: diffing two catalogs shows what Blizzard changed.
"""

import re
import sys

SUBCLASS = {
    1: 'Potions', 2: 'Elixirs', 3: 'Flasks', 4: 'Scrolls', 5: 'Food & Drink',
    6: 'Item Enhancement (permanent)', 7: 'Bandages', 8: 'Other', 0: 'Explosives / Consumable',
    14: 'Devices', 15: 'Item Enhancement (temporary)',
}


def main(src, dst):
    build = re.search(r'(\d{5,})', src)
    groups, unnamed = {}, 0
    for line in open(src, encoding='utf-8'):
        p = line.rstrip('\n').split('\t')
        if len(p) < 7 or p[3] in ('nil', ''):
            unnamed += 1
            continue
        sub = int(p[1]) if p[1] != 'nil' else -1
        tip = p[6]
        parts = [x.strip() for x in tip.split(' | ')]
        use = ' '.join(x for x in parts if x.startswith('Use:'))[4:].strip()
        if not use:
            m = re.search(r'\|\| DESC: (.*)$', tip)
            use = m.group(1).strip() if m else ''
        lvl = re.search(r'Requires Level (\d+)', tip)
        flags = []
        if 'Conjured Item' in parts: flags.append('conjured')
        if 'Binds when picked up' in parts: flags.append('BoP')
        if re.search(r'only (?:be used )?in(?:side)? ', use, re.I): flags.append('zone-locked')
        groups.setdefault(sub, []).append((int(p[0]), p[3], lvl.group(1) if lvl else '',
                                           p[4] if p[4] != 'nil' else '', ', '.join(flags),
                                           use.replace('|', '/')))

    total = sum(len(v) for v in groups.values())
    out = open(dst, 'w', encoding='utf-8', newline='\n')
    w = out.write
    w('# WoW: Forever consumables - client build %s\n\n' % (build.group(1) if build else '?'))
    w('Every item with classID 0 (Consumable) in the client\'s own item database, as reported\n')
    w('in game by Apotheca\'s `/apo scan` + `/apo scan2` (C_Item.GetItemInfoInstant over IDs\n')
    w('1-300000, then each tooltip and item spell). %d items. Generated by\n' % total)
    w('`Apotheca/Tools/consumables_reference.py`; the raw TSV is next to this file.\n')
    w('%d further consumable IDs exist in the client but never returned a name (mostly\n' % unnamed)
    w('internal or placeholder items); they are in the TSV only.\n\n')
    w('**Values are Forever\'s, not Vanilla\'s.** Tooltips are the client\'s own text: restore\n')
    w('amounts, buffs and durations all differ from 1.12 in places (Tough Jerky 58 vs 61,\n')
    w('Nightfin Soup +22 spell damage instead of mp5, base healthstones at the old Improved values).\n\n')
    w('**Diffing builds:** after a client update, re-scan, write a new file named for the new\n')
    w('build, and diff the two. Anything Wowhead lacks shows up here first (the Wowhead Forever\n')
    w('database had no Scroll of Protection at all on 2026-09-23; the client has all four).\n\n')
    w('Columns: item ID, name, required level, item spell ID (the buff it applies, for aura\n')
    w('matching), flags, and the tooltip\'s Use text. An empty Use means the client never\n')
    w('returned it, not that the item does nothing.\n\n')
    for sub in sorted(groups, key=lambda k: SUBCLASS.get(k, 'zz')):
        rows = sorted(groups[sub])
        w('## %s (%d)\n\n' % (SUBCLASS.get(sub, 'subclass %d' % sub), len(rows)))
        w('| ID | Name | Lvl | Spell | Flags | Use |\n|---:|---|---:|---:|---|---|\n')
        for r in rows:
            w('| %d | %s | %s | %s | %s | %s |\n' % r)
        w('\n')
    out.close()
    print('%d items -> %s' % (total, dst))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
